apiVersion: v1
kind: ConfigMap
metadata:
  name: agro-telemetry-config
data:
  AspNetCore_Environment: "${ENV}"
  ElasticApm__Enabled: "${ELASTIC_APM_ENABLED}"
  ElasticApm__ServerUrl: "${ELASTIC_APM_SERVER_URL}"
  ElasticApm__ServiceName: "${APM_SERVICE_NAME}"
  ElasticApm__Environment: "${ENV}"