apiVersion: v1
kind: ConfigMap
metadata:
  name: agro-telemetry-config
data:
  LoggerSettings__Provider: "${LOGGER_PROVIDER}"
  LoggerSettings__ServiceName: "${LOGGER_SERVICE_NAME}"

  ElasticLogs__Endpoint: "${ELASTIC_LOGS_ENDPOINT}"
  ElasticLogs__IndexPrefix: "${ELASTIC_LOGS_INDEX_PREFIX}"

  ElasticApm__Enabled: "${ELASTIC_APM_ENABLED}"
  ElasticApm__ServerUrl: "${ELASTIC_APM_SERVER_URL}"
  ElasticApm__ServiceName: "${ELASTIC_APM_SERVICE_NAME}"
  ElasticApm__Environment: "${ENV}"

  ASPNETCORE_ENVIRONMENT: "${ENV}"
  Jwt__Issuer: "${JWT_ISSUER}"

  CosmosDb__DatabaseId: "${COSMOSDB_DATABASE_ID}"

  KeyVault__VaultUri: "${KEYVAULT_URI}"
  KeyVault__Enabled: "${KEYVAULT_ENABLED}"