apiVersion: v1
kind: Secret
metadata:
  name: agro-telemetry-secret
type: Opaque
stringData:
  ConnectionStrings__TelemetryDbConnection: "${DB_CONNECTIONSTRING}"
  ConnectionStrings__ServiceBusConnection: "${SB_CONNECTIONSTRING}"
  ElasticLogs__ApiKey: "${ELASTIC_LOGS_API_KEY}"
  ElasticApm__SecretToken: "${ELASTIC_APM_SECRET_TOKEN}"
  Jwt__Key: "${JWT_KEY}"
