apiVersion: v1
kind: Secret
metadata:
  name: agro-telemetry-secret
type: Opaque
stringData:
  ConnectionStrings__AgroDbConnection: "${AGRODB_CONNECTIONSTRING}"
  ElasticApm__SecretToken: "${ELASTIC_APM_SECRET_TOKEN}"
