name: CI/CD - AgroSolutions.Telemetry - AKS

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**/README.md'
      - 'docs/**'

jobs:
  build-test-pushDockerImage:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.image_tag }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
          
      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore AgroSolutions.Telemetry.sln

      - name: Build
        run: dotnet build AgroSolutions.Telemetry.sln --configuration Release --no-restore
        
      - name: Architecture Tests
        run: dotnet test AgroSolutions.Telemetry.sln --filter "FullyQualifiedName~ArchitectureTests" --configuration Release --no-build --verbosity normal

      - name: Unit Tests
        run: dotnet test AgroSolutions.Telemetry.sln --filter "FullyQualifiedName~UnitTests" --configuration Release --no-build --verbosity normal
        
      - name: Integration Tests
        run: dotnet test AgroSolutions.Telemetry.sln --filter "FullyQualifiedName~IntegrationTests" --configuration Release --no-build --verbosity normal
        
      - name: Code Coverage
        run: dotnet test AgroSolutions.Telemetry.sln --configuration Release --no-build --collect:"XPlat Code Coverage" --logger "trx;LogFileName=test-results.trx"

      - name: Login to Azure Container Registry
        run: echo ${{ secrets.AZURE_ACR_PASSWORD }} | docker login acragro.azurecr.io -u ${{ vars.AZURE_ACR_USERNAME }} --password-stdin

      - name: Set Docker Image Tag
        id: set_tag
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "image_tag=${SHORT_SHA}" >> $GITHUB_OUTPUT
          
      - name: Build Docker Image
        run: |
          docker build -t acragro.azurecr.io/agrosolutions/telemetry/api:latest \
                       -t acragro.azurecr.io/agrosolutions/telemetry/api:${{ steps.set_tag.outputs.image_tag }} .

      - name: Push Docker Image to ACR
        run: |
          docker push acragro.azurecr.io/agrosolutions/telemetry/api:latest
          docker push acragro.azurecr.io/agrosolutions/telemetry/api:${{ steps.set_tag.outputs.image_tag }}
          
  deploy-dev:
    needs: build-test-pushDockerImage
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        run: az aks get-credentials --resource-group RG_AGRO --name aks-agro-telemetry --overwrite-existing
        
      - name: Apply Namespaces
        run: kubectl apply -f Kubernetes/namespace.yaml
        
      - name: Apply ConfigMap and Secret
        run: |
             export ENV="${{ vars.ENV }}"
             export JWT_ISSUER="${{ vars.JWT_ISSUER }}"
             export LOGGER_PROVIDER="${{ vars.LOGGER_PROVIDER }}"
             export LOGGER_SERVICE_NAME="${{ vars.SERVICE_NAME }}"
             export ELASTIC_APM_SERVICE_NAME="${{ vars.SERVICE_NAME }}"
             export ELASTIC_APM_ENABLED="${{ vars.ELASTIC_APM_ENABLED }}"
             export ELASTIC_APM_SERVER_URL="${{ vars.ELASTIC_APM_SERVER_URL }}"
             export ELASTIC_LOGS_ENDPOINT="${{ vars.ELASTIC_LOGS_ENDPOINT }}"
             export ELASTIC_LOGS_INDEX_PREFIX="${{ vars.ELASTIC_LOGS_INDEX_PREFIX }}"
             export COSMOSDB_DATABASE_ID="${{ secrets.COSMOSDB_DATABASE_ID }}"
             export JWT_KEY="${{ secrets.JWT_KEY }}"
             export ELASTIC_LOGS_API_KEY="${{ secrets.ELASTIC_LOGS_API_KEY }}"
             export ELASTIC_APM_SECRET_TOKEN="${{ secrets.ELASTIC_APM_SECRET_TOKEN }}"
             export DB_CONNECTIONSTRING="${{ secrets.DB_CONNECTIONSTRING }}"
             export SB_CONNECTIONSTRING="${{ secrets.SB_CONNECTIONSTRING }}"
             envsubst < Kubernetes/configmap.yaml | kubectl apply -n agro-telemetry-dev -f -            # aplica o configmap com substituição de variáveis
             envsubst < Kubernetes/secret.yaml | kubectl apply -n agro-telemetry-dev -f -               # aplica o secret com substituição de variáveis

      - name: Deploy to AKS - DEV
        run: |
             export IMAGE_TAG="${{ needs.build-test-pushDockerImage.outputs.image_tag }}"           # tag da imagem Docker
             envsubst < Kubernetes/deployment.yaml | kubectl apply -n agro-telemetry-dev -f -           # aplica o deployment com substituição de variáveis
             kubectl apply -f Kubernetes/service.yaml -n agro-telemetry-dev                             # aplica o service
             kubectl rollout restart deployment/agro-telemetry -n agro-telemetry-dev                        # força o restart para atualizar o secret/configmap
             kubectl rollout status deployment/agro-telemetry -n agro-telemetry-dev                         # aguarda o rollout completar
             
  deploy-uat:
    needs:
      - build-test-pushDockerImage
      - deploy-dev
    runs-on: ubuntu-latest
    environment: Staging

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        run: az aks get-credentials --resource-group RG_AGRO --name aks-agro-telemetry --overwrite-existing
        
      - name: Apply Namespaces
        run: kubectl apply -f Kubernetes/namespace.yaml
        
      - name: Apply ConfigMap and Secret
        run: |
             export ENV="${{ vars.ENV }}"
             export JWT_ISSUER="${{ vars.JWT_ISSUER }}"
             export LOGGER_PROVIDER="${{ vars.LOGGER_PROVIDER }}"
             export LOGGER_SERVICE_NAME="${{ vars.SERVICE_NAME }}"
             export ELASTIC_APM_SERVICE_NAME="${{ vars.SERVICE_NAME }}"
             export ELASTIC_APM_ENABLED="${{ vars.ELASTIC_APM_ENABLED }}"
             export ELASTIC_APM_SERVER_URL="${{ vars.ELASTIC_APM_SERVER_URL }}"
             export ELASTIC_LOGS_ENDPOINT="${{ vars.ELASTIC_LOGS_ENDPOINT }}"
             export ELASTIC_LOGS_INDEX_PREFIX="${{ vars.ELASTIC_LOGS_INDEX_PREFIX }}"
             export COSMOSDB_DATABASE_ID="${{ secrets.COSMOSDB_DATABASE_ID }}"
             export JWT_KEY="${{ secrets.JWT_KEY }}"
             export ELASTIC_LOGS_API_KEY="${{ secrets.ELASTIC_LOGS_API_KEY }}"
             export ELASTIC_APM_SECRET_TOKEN="${{ secrets.ELASTIC_APM_SECRET_TOKEN }}"
             export DB_CONNECTIONSTRING="${{ secrets.DB_CONNECTIONSTRING }}"
             export SB_CONNECTIONSTRING="${{ secrets.SB_CONNECTIONSTRING }}"
             envsubst < Kubernetes/configmap.yaml | kubectl apply -n agro-telemetry-uat -f -            # aplica o configmap com substituição de variáveis
             envsubst < Kubernetes/secret.yaml | kubectl apply -n agro-telemetry-uat -f -               # aplica o secret com substituição de variáveis

      # - name: Deploy to AKS - UAT
      #   run: |
      #        export IMAGE_TAG="${{ needs.build-test-pushDockerImage.outputs.image_tag }}"           # tag da imagem Docker
             # envsubst < Kubernetes/deployment.yaml | kubectl apply -n agro-telemetry-uat -f -           # aplica o deployment com substituição de variáveis
             # kubectl apply -f Kubernetes/service.yaml -n agro-telemetry-uat                             # aplica o service
             # kubectl rollout restart deployment/agro-telemetry -n agro-telemetry-uat                    # força o restart para atualizar o secret/configmap
             # kubectl rollout status deployment/agro-telemetry -n agro-telemetry-uat                     # aguarda o rollout completar

  deploy-prd:
    needs:
      - build-test-pushDockerImage
      - deploy-dev
      - deploy-uat
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: Production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        run: az aks get-credentials --resource-group RG_AGRO --name aks-agro-telemetry --overwrite-existing
        
      - name: Apply Namespaces
        run: kubectl apply -f Kubernetes/namespace.yaml
        
      - name: Apply ConfigMap and Secret
        run: |
             export ENV="${{ vars.ENV }}"
             export JWT_ISSUER="${{ vars.JWT_ISSUER }}"
             export LOGGER_PROVIDER="${{ vars.LOGGER_PROVIDER }}"
             export LOGGER_SERVICE_NAME="${{ vars.SERVICE_NAME }}"
             export ELASTIC_APM_SERVICE_NAME="${{ vars.SERVICE_NAME }}"
             export ELASTIC_APM_ENABLED="${{ vars.ELASTIC_APM_ENABLED }}"
             export ELASTIC_APM_SERVER_URL="${{ vars.ELASTIC_APM_SERVER_URL }}"
             export ELASTIC_LOGS_ENDPOINT="${{ vars.ELASTIC_LOGS_ENDPOINT }}"
             export ELASTIC_LOGS_INDEX_PREFIX="${{ vars.ELASTIC_LOGS_INDEX_PREFIX }}"
             export COSMOSDB_DATABASE_ID="${{ secrets.COSMOSDB_DATABASE_ID }}"
             export JWT_KEY="${{ secrets.JWT_KEY }}"
             export ELASTIC_LOGS_API_KEY="${{ secrets.ELASTIC_LOGS_API_KEY }}"
             export ELASTIC_APM_SECRET_TOKEN="${{ secrets.ELASTIC_APM_SECRET_TOKEN }}"
             export DB_CONNECTIONSTRING="${{ secrets.DB_CONNECTIONSTRING }}"
             export SB_CONNECTIONSTRING="${{ secrets.SB_CONNECTIONSTRING }}"
             envsubst < Kubernetes/configmap.yaml | kubectl apply -n agro-telemetry -f -            # aplica o configmap com substituição de variáveis
             envsubst < Kubernetes/secret.yaml | kubectl apply -n agro-telemetry -f -               # aplica o secret com substituição de variáveis

      - name: Deploy to AKS - PRD
        run: |
             export IMAGE_TAG="${{ needs.build-test-pushDockerImage.outputs.image_tag }}"       # tag da imagem Docker
             envsubst < Kubernetes/deployment.yaml | kubectl apply -n agro-telemetry -f -           # aplica o deployment com substituição de variáveis
             kubectl apply -f Kubernetes/service.yaml -n agro-telemetry                             # aplica o service
             kubectl rollout restart deployment/agro-telemetry -n agro-telemetry                    # força o restart para atualizar o secret/configmap
             kubectl rollout status deployment/agro-telemetry -n agro-telemetry                     # aguarda o rollout completar
      
      - name: Deploy HPA
        run: |
             kubectl apply -f Kubernetes/hpa.yaml -n agro-telemetry                                  # aplica o HPA